### ISSUE TITLE
generator.sh error in MAC YOSHIMITSU

### ISSUE THREAD

**Issue by margotpaon** [forknote/cryptonote-generator#21]
margotgarcia:generator rubens.garcia$ bash generator.sh -f sneakcoin.json -c '-j3'
Traceback (most recent call last):
  File "lib/environment_variables.py", line 31, in <module>
    config = json.load(json_data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 290, in load
    *_kw)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 2 column 2 (char 3)
Remove temporary files...
margotgarcia:generator rubens.garcia$ sudo bash generator.sh -f sneakcoin.json -c '-j3'
Password:
Traceback (most recent call last):
  File "lib/environment_variables.py", line 31, in <module>
    config = json.load(json_data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    *_kw)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 2 column 2 (char 3)
Remove temporary files...

**Comment by pmitchev** [comment]
Can you share your json file?

**Comment by pmitchev** [comment]
Unable to replicate. Probably the bug is already fixed
